  version: '3.8'

  services:
    web:
      build: .
      expose:
        - "5000"
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
      depends_on:
        - redis
    redis:
      image: "redis:latest"
      ports:
        - 6379:6379
      volumes:
        - redis-data:/data
    nginx:
      image: "nginx:latest"
      ports:
        - 5000:5000
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - web
  volumes:
      redis-data: